<a href="https://colab.research.google.com/github/MahmudulRifat13/ML-Algorithm/blob/main/Multiple_Variable_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
import numpy as np
import pandas as pd
from sklearn import linear_model
import math
import warnings
warnings.filterwarnings('ignore')


In [56]:
df=pd.read_csv("/content/hiring.csv")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [57]:
pip install word2number

In [58]:
from word2number import w2n

In [59]:
df.experience=df.experience.fillna('zero')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [60]:
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [61]:
newdf=math.ceil(df["test_score(out of 10)"].mean())
newdf

8

In [62]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(newdf)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [63]:
reg=linear_model.LinearRegression()

In [64]:
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df[['salary($)']])

LinearRegression()

In [65]:
reg.predict([[2,9,6]])

array([[53205.96797671]])

In [66]:
reg.predict([[12,10,10]])

array([[92002.18340611]])

In [67]:
reg.coef_

array([[2812.95487627, 1845.70596798, 2205.24017467]])

In [68]:
reg.intercept_

array([17737.26346434])

In [69]:
(2812.95487627*2)+(1845.70596798*9)+(2205.24017467*6)+17737.26346434

53205.96797672001